### ISSUE TITLE
Report abuse mechanism

### ISSUE THREAD

**Issue by Morishiri** [loophole/website#3]
API route was provided in https://github.com/loophole/api/pull/7, create a modal to use it on webpage. It should be located in footer and should contain fields for:
- reported site url
- message
- optional email address

Only available for registered users.

@amankalra172  any additional requirements?

**Comment by amankalra172** [comment]
Why do we limit it to registered users? Can it not be open to all users?

**Comment by Morishiri** [comment]
It is now

**Comment by Morishiri** [comment]
done
